import { Element } from '../constants';

export const actinides: Element[] = [
  {
    atomicNumber: 89,
    symbol: "Ac",
    name: "Actinium",
    atomicMass: 227,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 6d¹ 7s²",
    electronegativity: 1.1,
    atomicRadius: 215,
    ionizationEnergy: 5.17,
    meltingPoint: 1050,
    boilingPoint: 3200,
    density: 10.07,
    state: "solid",
    discoveryYear: 1899,
    description: "Actinium is a soft, silvery-white radioactive metal. It glows in the dark with a pale blue light due to its intense radioactivity.",
    uses: ["Neutron source", "Medical research"],
  },
  {
    atomicNumber: 90,
    symbol: "Th",
    name: "Thorium",
    atomicMass: 232.04,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 6d² 7s²",
    electronegativity: 1.3,
    atomicRadius: 206,
    ionizationEnergy: 6.08,
    meltingPoint: 1750,
    boilingPoint: 4820,
    density: 11.72,
    state: "solid",
    discoveryYear: 1829,
    description: "Thorium is a soft, very ductile, silver-white, radioactive actinide metal. It is pyrophoric in powder form and it is attacked slowly by water.",
    uses: ["Nuclear fuel", "High-temperature ceramics", "Aircraft engines"],
  },
  {
    atomicNumber: 91,
    symbol: "Pa",
    name: "Protactinium",
    atomicMass: 231.04,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: 1.5,
    atomicRadius: 200,
    ionizationEnergy: 5.89,
    meltingPoint: 1568,
    boilingPoint: 4027,
    density: 15.37,
    state: "solid",
    discoveryYear: 1913,
    description: "Protactinium is a dense, silvery-gray radioactive actinide metal. It is one of the rarest and most expensive naturally occurring elements.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 92,
    symbol: "U",
    name: "Uranium",
    atomicMass: 238.03,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: 1.38,
    atomicRadius: 196,
    ionizationEnergy: 6.194,
    meltingPoint: 1132.2,
    boilingPoint: 3818,
    density: 19.1,
    state: "solid",
    discoveryYear: 1789,
    description: "Uranium is a silvery-white, weakly radioactive metal. It has the highest atomic weight of the naturally occurring elements. It is approximately 70% denser than lead.",
    uses: ["Nuclear fuel", "Nuclear weapons", "Radiation shielding"],
  },
  {
    atomicNumber: 93,
    symbol: "Np",
    name: "Neptunium",
    atomicMass: 237,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: 1.36,
    atomicRadius: 190,
    ionizationEnergy: 6.266,
    meltingPoint: 644,
    boilingPoint: 3902,
    density: 20.45,
    state: "solid",
    discoveryYear: 1940,
    description: "Neptunium is a silvery radioactive metal. It is the first transuranic element and was produced by bombarding uranium with neutrons.",
    uses: ["Nuclear detectors", "Nuclear batteries"],
  },
  {
    atomicNumber: 94,
    symbol: "Pu",
    name: "Plutonium",
    atomicMass: 244,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    electronegativity: 1.28,
    atomicRadius: 187,
    ionizationEnergy: 6.026,
    meltingPoint: 640,
    boilingPoint: 3228,
    density: 19.82,
    state: "solid",
    discoveryYear: 1940,
    description: "Plutonium is a radioactive, silver-gray metal that tarnishes in air. It is warm to the touch because of the energy released by alpha decay.",
    uses: ["Nuclear weapons", "Nuclear reactors", "Spacecraft power"],
  },
  {
    atomicNumber: 95,
    symbol: "Am",
    name: "Americium",
    atomicMass: 243,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    electronegativity: 1.3,
    atomicRadius: 184,
    ionizationEnergy: 5.993,
    meltingPoint: 1176,
    boilingPoint: 2011,
    density: 13.67,
    state: "solid",
    discoveryYear: 1944,
    description: "Americium is a silvery-white, synthetic radioactive metal. It is commonly used in household smoke detectors.",
    uses: ["Smoke detectors", "Industrial gauges", "Neutron sources"],
  },
  {
    atomicNumber: 96,
    symbol: "Cm",
    name: "Curium",
    atomicMass: 247,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: 1.3,
    atomicRadius: 169,
    ionizationEnergy: 5.991,
    meltingPoint: 1345,
    boilingPoint: 3110,
    density: 13.51,
    state: "solid",
    discoveryYear: 1944,
    description: "Curium is a hard, dense, silvery radioactive metal that tarnishes in air and is more electropositive than aluminum. All isotopes of curium are radioactive.",
    uses: ["Scientific research", "Alpha particle sources", "Radioisotope thermoelectric generators"],
  },
  {
    atomicNumber: 97,
    symbol: "Bk",
    name: "Berkelium",
    atomicMass: 247,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.23,
    meltingPoint: 1050,
    boilingPoint: null,
    density: 14.78,
    state: "solid",
    discoveryYear: 1949,
    description: "Berkelium is a silvery-white, radioactive actinide metal. It was named after Berkeley, California, where it was first synthesized.",
    uses: ["Scientific research", "Creating other elements"],
  },
  {
    atomicNumber: 98,
    symbol: "Cf",
    name: "Californium",
    atomicMass: 251,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.3,
    meltingPoint: 900,
    boilingPoint: null,
    density: 15.1,
    state: "solid",
    discoveryYear: 1950,
    description: "Californium is a radioactive actinide element. It is a strong neutron emitter, which makes it useful for neutron moisture gauges and starting nuclear reactors.",
    uses: ["Neutron moisture detectors", "Metal detectors", "Cancer treatment"],
  },
  {
    atomicNumber: 99,
    symbol: "Es",
    name: "Einsteinium",
    atomicMass: 252,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.42,
    meltingPoint: 860,
    boilingPoint: null,
    density: 8.84,
    state: "solid",
    discoveryYear: 1952,
    description: "Einsteinium is a synthetic element named after Albert Einstein. It is the seventh transuranic element and has no known practical applications beyond basic research.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 100,
    symbol: "Fm",
    name: "Fermium",
    atomicMass: 257,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹² 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.5,
    meltingPoint: 1527,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1952,
    description: "Fermium is a synthetic element named after Enrico Fermi. It was discovered in the debris of the first hydrogen bomb explosion.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 101,
    symbol: "Md",
    name: "Mendelevium",
    atomicMass: 258,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.58,
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1955,
    description: "Mendelevium is a synthetic element named after Dmitri Mendeleev. It has only been produced in very small amounts.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 102,
    symbol: "No",
    name: "Nobelium",
    atomicMass: 259,
    category: "actinide",
    group: null,
    period: 7,
    block: "f",
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 6.65,
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1958,
    description: "Nobelium is a synthetic element named after Alfred Nobel. Like other transuranic elements, it is highly radioactive and has a short half-life.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 103,
    symbol: "Lr",
    name: "Lawrencium",
    atomicMass: 266,
    category: "actinide",
    group: null,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: 1.3,
    atomicRadius: null,
    ionizationEnergy: 4.9,
    meltingPoint: 1627,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1961,
    description: "Lawrencium is a synthetic element named after Ernest Lawrence, inventor of the cyclotron. It is highly unstable, with a very short half-life.",
    uses: ["Scientific research"],
  }
];
