
import { Element } from '../constants';

export const alkalineEarthMetals: Element[] = [
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth",
    group: 2,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s²",
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 9.323,
    meltingPoint: 1287,
    boilingPoint: 2469,
    density: 1.85,
    state: "solid",
    discoveryYear: 1798,
    description: "Beryllium is a relatively rare element with steel-gray, strong, lightweight and brittle properties.",
    uses: ["X-ray windows", "Aerospace components", "Nuclear reactors"],
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth",
    group: 2,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s²",
    electronegativity: 1.31,
    atomicRadius: 160,
    ionizationEnergy: 7.646,
    meltingPoint: 650,
    boilingPoint: 1090,
    density: 1.738,
    state: "solid",
    discoveryYear: 1808,
    description: "Magnesium is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
    uses: ["Lightweight alloys", "Fireworks", "Medicine"],
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth",
    group: 2,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s²",
    electronegativity: 1.0,
    atomicRadius: 197,
    ionizationEnergy: 6.113,
    meltingPoint: 842,
    boilingPoint: 1484,
    density: 1.54,
    state: "solid",
    discoveryYear: 1808,
    description: "Calcium is a soft, reactive metal that is essential for living organisms. It is the most abundant metal in the human body.",
    uses: ["Construction (cement)", "Food fortification", "Metallurgy"],
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline-earth",
    group: 2,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s²",
    electronegativity: 0.95,
    atomicRadius: 215,
    ionizationEnergy: 5.695,
    meltingPoint: 777,
    boilingPoint: 1377,
    density: 2.64,
    state: "solid",
    discoveryYear: 1790,
    description: "Strontium is a soft, silvery, yellowish metallic element that is highly reactive chemically. It turns yellow when exposed to air.",
    uses: ["Fireworks", "Ceramic ferrites", "Glass for color TVs"],
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.33,
    category: "alkaline-earth",
    group: 2,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s²",
    electronegativity: 0.89,
    atomicRadius: 222,
    ionizationEnergy: 5.212,
    meltingPoint: 727,
    boilingPoint: 1897,
    density: 3.51,
    state: "solid",
    discoveryYear: 1808,
    description: "Barium is a soft, silvery alkaline earth metal. It is never found in nature as a free element due to its high chemical reactivity.",
    uses: ["Oil and gas industry", "X-ray imaging", "Fireworks"],
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline-earth",
    group: 2,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s²",
    electronegativity: 0.9,
    atomicRadius: 220,
    ionizationEnergy: 5.279,
    meltingPoint: 700,
    boilingPoint: 1737,
    density: 5.5,
    state: "solid",
    discoveryYear: 1898,
    description: "Radium is a brilliant white, luminescent, highly radioactive metal. It decays into radon, an inert radioactive gas.",
    uses: ["Historical luminous paints", "Cancer treatment (historical)", "Research"],
  }
];
