
import { Element } from '../constants';

export const alkaliMetals: Element[] = [
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali-metal",
    group: 1,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s¹",
    electronegativity: 0.98,
    atomicRadius: 152,
    ionizationEnergy: 5.392,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    density: 0.534,
    state: "solid",
    discoveryYear: 1817,
    description: "Lithium is the lightest metal and the least dense solid element. It is highly reactive and flammable.",
    uses: ["Batteries", "Medication", "Aerospace alloys"],
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.990,
    category: "alkali-metal",
    group: 1,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s¹",
    electronegativity: 0.93,
    atomicRadius: 186,
    ionizationEnergy: 5.139,
    meltingPoint: 97.72,
    boilingPoint: 883,
    density: 0.968,
    state: "solid",
    discoveryYear: 1807,
    description: "Sodium is a soft, silvery-white, highly reactive metal. It is the sixth most abundant element in the Earth's crust.",
    uses: ["Salt (NaCl)", "Street lights", "Soap manufacturing"],
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    group: 1,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s¹",
    electronegativity: 0.82,
    atomicRadius: 227,
    ionizationEnergy: 4.341,
    meltingPoint: 63.38,
    boilingPoint: 759,
    density: 0.862,
    state: "solid",
    discoveryYear: 1807,
    description: "Potassium is a soft, silvery-white metal similar to sodium. It reacts rapidly with water to produce hydrogen.",
    uses: ["Fertilizers", "Soap making", "Food additives"],
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali-metal",
    group: 1,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s¹",
    electronegativity: 0.82,
    atomicRadius: 248,
    ionizationEnergy: 4.177,
    meltingPoint: 39.31,
    boilingPoint: 688,
    density: 1.53,
    state: "solid",
    discoveryYear: 1861,
    description: "Rubidium is a very soft, silvery-white metal in the alkali metal group. It is one of the most reactive elements and rapidly oxidizes in air.",
    uses: ["Atomic clocks", "Electronics", "Research"],
  },
  // Continuing with additional alkali metals
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: 132.91,
    category: "alkali-metal",
    group: 1,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s¹",
    electronegativity: 0.79,
    atomicRadius: 265,
    ionizationEnergy: 3.894,
    meltingPoint: 28.44,
    boilingPoint: 671,
    density: 1.93,
    state: "solid",
    discoveryYear: 1860,
    description: "Cesium is a soft, silvery-gold alkali metal with a melting point of 28.5°C, which makes it one of only five elemental metals that are liquid at or near room temperature.",
    uses: ["Atomic clocks", "Photoelectric cells", "Vacuum tubes"],
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali-metal",
    group: 1,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s¹",
    electronegativity: 0.7,
    atomicRadius: 270,
    ionizationEnergy: 4.073,
    meltingPoint: 27,
    boilingPoint: 677,
    density: 1.87,
    state: "solid",
    discoveryYear: 1939,
    description: "Francium is the second-rarest naturally occurring element. It is highly radioactive with a short half-life, making it difficult to study and use.",
    uses: ["Research", "Nuclear physics studies"],
  }
];
