import { Element } from '../constants';

export const lanthanides: Element[] = [
  {
    atomicNumber: 57,
    symbol: "La",
    name: "Lanthanum",
    atomicMass: 138.91,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    electronegativity: 1.1,
    atomicRadius: 187,
    ionizationEnergy: 5.577,
    meltingPoint: 920,
    boilingPoint: 3464,
    density: 6.15,
    state: "solid",
    discoveryYear: 1839,
    description: "Lanthanum is a soft, ductile, silvery-white metal that tarnishes rapidly when exposed to air. It is the first element in the lanthanide series.",
    uses: ["Optical glasses", "Carbon arc lamps", "Hydrogen storage"],
  },
  {
    atomicNumber: 58,
    symbol: "Ce",
    name: "Cerium",
    atomicMass: 140.12,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: 1.12,
    atomicRadius: 182,
    ionizationEnergy: 5.539,
    meltingPoint: 798,
    boilingPoint: 3443,
    density: 6.77,
    state: "solid",
    discoveryYear: 1803,
    description: "Cerium is a soft, ductile, and silvery-white metal that oxidizes readily in air. It is the most abundant of the rare earth elements.",
    uses: ["Catalytic converters", "Self-cleaning ovens", "Glass polishing"],
  },
  {
    atomicNumber: 59,
    symbol: "Pr",
    name: "Praseodymium",
    atomicMass: 140.91,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f³ 6s²",
    electronegativity: 1.13,
    atomicRadius: 182,
    ionizationEnergy: 5.464,
    meltingPoint: 931,
    boilingPoint: 3520,
    density: 6.77,
    state: "solid",
    discoveryYear: 1885,
    description: "Praseodymium is a soft, silvery, malleable and ductile metal. It develops a green oxide coating when exposed to air.",
    uses: ["Magnets", "Special glasses", "Ceramic colorant"],
  },
  {
    atomicNumber: 60,
    symbol: "Nd",
    name: "Neodymium",
    atomicMass: 144.24,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    electronegativity: 1.14,
    atomicRadius: 181,
    ionizationEnergy: 5.525,
    meltingPoint: 1016,
    boilingPoint: 3074,
    density: 7.01,
    state: "solid",
    discoveryYear: 1885,
    description: "Neodymium is a soft, silvery metal that tarnishes in air. It is one of the most abundant rare earth elements.",
    uses: ["Powerful permanent magnets", "Lasers", "Colored glass"],
  },
  // Continuing with more lanthanides
  {
    atomicNumber: 61,
    symbol: "Pm",
    name: "Promethium",
    atomicMass: 145,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    electronegativity: 1.13,
    atomicRadius: 183,
    ionizationEnergy: 5.582,
    meltingPoint: 1042,
    boilingPoint: 3000,
    density: 7.26,
    state: "solid",
    discoveryYear: 1945,
    description: "Promethium is a radioactive element that doesn't occur naturally on Earth. All its isotopes are radioactive.",
    uses: ["Batteries for spacecraft", "Portable X-ray sources", "Nuclear powered microbatteries"],
  },
  {
    atomicNumber: 62,
    symbol: "Sm",
    name: "Samarium",
    atomicMass: 150.36,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    electronegativity: 1.17,
    atomicRadius: 180,
    ionizationEnergy: 5.644,
    meltingPoint: 1072,
    boilingPoint: 1794,
    density: 7.52,
    state: "solid",
    discoveryYear: 1879,
    description: "Samarium is a fairly hard silvery metal that readily oxidizes in air. It is one of the more reactive lanthanide elements.",
    uses: ["Permanent magnets", "Cancer treatment", "Nuclear reactors"],
  },
  {
    atomicNumber: 63,
    symbol: "Eu",
    name: "Europium",
    atomicMass: 151.96,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    electronegativity: 1.2,
    atomicRadius: 180,
    ionizationEnergy: 5.67,
    meltingPoint: 822,
    boilingPoint: 1529,
    density: 5.24,
    state: "solid",
    discoveryYear: 1901,
    description: "Europium is a moderately hard, silvery metal. It is the most reactive of the rare earth elements and quickly oxidizes in air.",
    uses: ["Red phosphors for TVs", "Anti-counterfeiting marks in Euro banknotes", "Nuclear reactors"],
  },
  {
    atomicNumber: 64,
    symbol: "Gd",
    name: "Gadolinium",
    atomicMass: 157.25,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: 1.2,
    atomicRadius: 180,
    ionizationEnergy: 6.15,
    meltingPoint: 1313,
    boilingPoint: 3273,
    density: 7.90,
    state: "solid",
    discoveryYear: 1880,
    description: "Gadolinium is a silvery-white, malleable, and ductile rare earth metal. It has remarkable magnetic properties and the highest neutron absorption cross-section of any stable element.",
    uses: ["MRI contrast agents", "Nuclear reactors", "Data storage"],
  },
  {
    atomicNumber: 65,
    symbol: "Tb",
    name: "Terbium",
    atomicMass: 158.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    electronegativity: 1.2,
    atomicRadius: 177,
    ionizationEnergy: 5.864,
    meltingPoint: 1356,
    boilingPoint: 3230,
    density: 8.23,
    state: "solid",
    discoveryYear: 1843,
    description: "Terbium is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. It is relatively stable in air compared to other lanthanides.",
    uses: ["Green phosphors", "Solid-state devices", "Naval sonar systems"],
  },
  {
    atomicNumber: 66,
    symbol: "Dy",
    name: "Dysprosium",
    atomicMass: 162.50,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    electronegativity: 1.22,
    atomicRadius: 178,
    ionizationEnergy: 5.939,
    meltingPoint: 1412,
    boilingPoint: 2567,
    density: 8.55,
    state: "solid",
    discoveryYear: 1886,
    description: "Dysprosium is a rare earth element with a metallic, bright silver luster. It is relatively stable in air at room temperature, but dissolves readily in dilute acids.",
    uses: ["Nuclear reactors", "Data storage devices", "High-power magnets"],
  },
  {
    atomicNumber: 67,
    symbol: "Ho",
    name: "Holmium",
    atomicMass: 164.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    electronegativity: 1.23,
    atomicRadius: 176,
    ionizationEnergy: 6.022,
    meltingPoint: 1474,
    boilingPoint: 2700,
    density: 8.80,
    state: "solid",
    discoveryYear: 1878,
    description: "Holmium is a relatively soft and malleable silvery-white metal. It has the highest magnetic permeability of any element and unusually strong magnetic properties.",
    uses: ["Magnets", "Nuclear reactors", "Laser equipment"],
  },
  {
    atomicNumber: 68,
    symbol: "Er",
    name: "Erbium",
    atomicMass: 167.26,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    electronegativity: 1.24,
    atomicRadius: 176,
    ionizationEnergy: 6.108,
    meltingPoint: 1529,
    boilingPoint: 2868,
    density: 9.07,
    state: "solid",
    discoveryYear: 1843,
    description: "Erbium is a silvery-white solid metal that is soft, malleable, and has a bright, metallic luster. It is fairly stable in air but dissolves readily in acids.",
    uses: ["Fiber-optic communications", "Lasers", "Metallurgy"],
  },
  {
    atomicNumber: 69,
    symbol: "Tm",
    name: "Thulium",
    atomicMass: 168.93,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    electronegativity: 1.25,
    atomicRadius: 176,
    ionizationEnergy: 6.184,
    meltingPoint: 1545,
    boilingPoint: 1950,
    density: 9.32,
    state: "solid",
    discoveryYear: 1879,
    description: "Thulium is a bright, silvery-white metal with a slight tinge of blue. It is the least abundant naturally occurring lanthanide element.",
    uses: ["Portable X-ray machines", "Lasers", "Ceramic magnetic materials"],
  },
  {
    atomicNumber: 70,
    symbol: "Yb",
    name: "Ytterbium",
    atomicMass: 173.05,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "f",
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    electronegativity: 1.1,
    atomicRadius: 176,
    ionizationEnergy: 6.254,
    meltingPoint: 819,
    boilingPoint: 1196,
    density: 6.90,
    state: "solid",
    discoveryYear: 1878,
    description: "Ytterbium is a soft, malleable, and ductile chemical element that displays a bright, silvery luster. It is readily attacked by air and water.",
    uses: ["Fiber optic technology", "Stress gauges", "Portable X-ray machines"],
  },
  {
    atomicNumber: 71,
    symbol: "Lu",
    name: "Lutetium",
    atomicMass: 174.97,
    category: "lanthanide",
    group: null,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: 1.27,
    atomicRadius: 174,
    ionizationEnergy: 5.426,
    meltingPoint: 1663,
    boilingPoint: 3402,
    density: 9.84,
    state: "solid",
    discoveryYear: 1907,
    description: "Lutetium is a silvery white metal, which resists corrosion in dry air, but not in moist air. It is considered the hardest and densest of the lanthanides.",
    uses: ["Petroleum cracking catalysts", "PET scan detectors", "LEDs"],
  }
];
