
import { Element } from "../constants";

// Elements from groups 1-2 and 13-18 (excluding noble gases)
export const mainGroupElements: Element[] = [
  // Group 1: Alkali Metals
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    group: 1,
    period: 1,
    block: "s",
    electronConfiguration: "1s¹",
    electronegativity: 2.2,
    atomicRadius: 38,
    ionizationEnergy: 13.598,
    meltingPoint: -259.16,
    boilingPoint: -252.879,
    density: 0.00008988,
    state: "gas",
    discoveryYear: 1766,
    description: "Hydrogen is the lightest and most abundant element in the universe. It is present in water and in all organic compounds.",
    uses: ["Fuel", "Making ammonia", "Hydrogenation of oils to make fats"],
  },
  {
    atomicNumber: 3,
    symbol: "Li",
    name: "Lithium",
    atomicMass: 6.94,
    category: "alkali-metal",
    group: 1,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s¹",
    electronegativity: 0.98,
    atomicRadius: 152,
    ionizationEnergy: 5.392,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    density: 0.534,
    state: "solid",
    discoveryYear: 1817,
    description: "Lithium is the lightest metal and the least dense solid element. It is highly reactive and flammable.",
    uses: ["Batteries", "Medication", "Aerospace alloys"],
  },
  {
    atomicNumber: 11,
    symbol: "Na",
    name: "Sodium",
    atomicMass: 22.990,
    category: "alkali-metal",
    group: 1,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s¹",
    electronegativity: 0.93,
    atomicRadius: 186,
    ionizationEnergy: 5.139,
    meltingPoint: 97.72,
    boilingPoint: 883,
    density: 0.968,
    state: "solid",
    discoveryYear: 1807,
    description: "Sodium is a soft, silvery-white, highly reactive metal. It is the sixth most abundant element in the Earth's crust.",
    uses: ["Salt (NaCl)", "Street lights", "Soap manufacturing"],
  },
  {
    atomicNumber: 19,
    symbol: "K",
    name: "Potassium",
    atomicMass: 39.098,
    category: "alkali-metal",
    group: 1,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s¹",
    electronegativity: 0.82,
    atomicRadius: 227,
    ionizationEnergy: 4.341,
    meltingPoint: 63.38,
    boilingPoint: 759,
    density: 0.862,
    state: "solid",
    discoveryYear: 1807,
    description: "Potassium is a soft, silvery-white metal similar to sodium. It reacts rapidly with water to produce hydrogen.",
    uses: ["Fertilizers", "Soap making", "Food additives"],
  },
  {
    atomicNumber: 37,
    symbol: "Rb",
    name: "Rubidium",
    atomicMass: 85.468,
    category: "alkali-metal",
    group: 1,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s¹",
    electronegativity: 0.82,
    atomicRadius: 248,
    ionizationEnergy: 4.177,
    meltingPoint: 39.31,
    boilingPoint: 688,
    density: 1.532,
    state: "solid",
    discoveryYear: 1861,
    description: "Rubidium is a very soft, silvery-white metal in the alkali metal group. It is highly reactive, with properties similar to other alkali metals, including rapid oxidation in air.",
    uses: ["Atomic clocks", "Electronics", "Medical imaging"],
  },
  {
    atomicNumber: 55,
    symbol: "Cs",
    name: "Cesium",
    atomicMass: 132.905,
    category: "alkali-metal",
    group: 1,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s¹",
    electronegativity: 0.79,
    atomicRadius: 265,
    ionizationEnergy: 3.894,
    meltingPoint: 28.44,
    boilingPoint: 671,
    density: 1.93,
    state: "solid",
    discoveryYear: 1860,
    description: "Cesium is a soft, silvery-gold alkali metal with a melting point of 28 °C, making it one of only five elemental metals that are liquid at room temperature.",
    uses: ["Atomic clocks", "Oil drilling", "Photoelectric cells"],
  },
  {
    atomicNumber: 87,
    symbol: "Fr",
    name: "Francium",
    atomicMass: 223,
    category: "alkali-metal",
    group: 1,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s¹",
    electronegativity: 0.7,
    atomicRadius: 270,
    ionizationEnergy: 4.073,
    meltingPoint: 27,
    boilingPoint: 677,
    density: null,
    state: "solid",
    discoveryYear: 1939,
    description: "Francium is the second-rarest naturally occurring element after astatine. It is highly radioactive with a short half-life, making it extremely rare in nature.",
    uses: ["Research", "Basic science studies"],
  },
  
  // Group 2: Alkaline Earth Metals
  {
    atomicNumber: 4,
    symbol: "Be",
    name: "Beryllium",
    atomicMass: 9.0122,
    category: "alkaline-earth",
    group: 2,
    period: 2,
    block: "s",
    electronConfiguration: "[He] 2s²",
    electronegativity: 1.57,
    atomicRadius: 112,
    ionizationEnergy: 9.323,
    meltingPoint: 1287,
    boilingPoint: 2469,
    density: 1.85,
    state: "solid",
    discoveryYear: 1798,
    description: "Beryllium is a relatively rare element with steel-gray, strong, lightweight and brittle properties.",
    uses: ["X-ray windows", "Aerospace components", "Nuclear reactors"],
  },
  {
    atomicNumber: 12,
    symbol: "Mg",
    name: "Magnesium",
    atomicMass: 24.305,
    category: "alkaline-earth",
    group: 2,
    period: 3,
    block: "s",
    electronConfiguration: "[Ne] 3s²",
    electronegativity: 1.31,
    atomicRadius: 160,
    ionizationEnergy: 7.646,
    meltingPoint: 650,
    boilingPoint: 1090,
    density: 1.738,
    state: "solid",
    discoveryYear: 1808,
    description: "Magnesium is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table.",
    uses: ["Lightweight alloys", "Fireworks", "Medicine"],
  },
  {
    atomicNumber: 20,
    symbol: "Ca",
    name: "Calcium",
    atomicMass: 40.078,
    category: "alkaline-earth",
    group: 2,
    period: 4,
    block: "s",
    electronConfiguration: "[Ar] 4s²",
    electronegativity: 1.0,
    atomicRadius: 197,
    ionizationEnergy: 6.113,
    meltingPoint: 842,
    boilingPoint: 1484,
    density: 1.54,
    state: "solid",
    discoveryYear: 1808,
    description: "Calcium is a soft, reactive metal that is essential for living organisms. It is the most abundant metal in the human body.",
    uses: ["Construction (cement)", "Food fortification", "Metallurgy"],
  },
  {
    atomicNumber: 38,
    symbol: "Sr",
    name: "Strontium",
    atomicMass: 87.62,
    category: "alkaline-earth",
    group: 2,
    period: 5,
    block: "s",
    electronConfiguration: "[Kr] 5s²",
    electronegativity: 0.95,
    atomicRadius: 215,
    ionizationEnergy: 5.695,
    meltingPoint: 777,
    boilingPoint: 1377,
    density: 2.64,
    state: "solid",
    discoveryYear: 1790,
    description: "Strontium is a soft, silvery-yellow alkaline earth metal that is highly reactive chemically. The metal forms a dark oxide layer when it is exposed to air.",
    uses: ["Fireworks", "Ceramic magnets", "Glow-in-the-dark toys"],
  },
  {
    atomicNumber: 56,
    symbol: "Ba",
    name: "Barium",
    atomicMass: 137.327,
    category: "alkaline-earth",
    group: 2,
    period: 6,
    block: "s",
    electronConfiguration: "[Xe] 6s²",
    electronegativity: 0.89,
    atomicRadius: 222,
    ionizationEnergy: 5.212,
    meltingPoint: 727,
    boilingPoint: 1897,
    density: 3.51,
    state: "solid",
    discoveryYear: 1808,
    description: "Barium is a soft, silvery alkaline earth metal that oxidizes rapidly in air. It is never found in nature as a free element.",
    uses: ["Medical imaging", "Spark plugs", "Glassmaking"],
  },
  {
    atomicNumber: 88,
    symbol: "Ra",
    name: "Radium",
    atomicMass: 226,
    category: "alkaline-earth",
    group: 2,
    period: 7,
    block: "s",
    electronConfiguration: "[Rn] 7s²",
    electronegativity: 0.9,
    atomicRadius: 220,
    ionizationEnergy: 5.279,
    meltingPoint: 700,
    boilingPoint: 1737,
    density: 5.5,
    state: "solid",
    discoveryYear: 1898,
    description: "Radium is a radioactive, luminescent, silvery-white metal. It is extremely radioactive and its decay product, radon gas, is also radioactive.",
    uses: ["Historical luminous watches", "Cancer treatment (historical)", "Research"],
  },
  
  // Group 13 (IIIA)
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    group: 13,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    atomicRadius: 85,
    ionizationEnergy: 8.298,
    meltingPoint: 2076,
    boilingPoint: 3927,
    density: 2.34,
    state: "solid",
    discoveryYear: 1808,
    description: "Boron is a semiconductor with properties between metals and non-metals. It is never found free in nature.",
    uses: ["Glass manufacturing", "Detergents", "Agriculture"],
  },
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition",
    group: 13,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    atomicRadius: 143,
    ionizationEnergy: 5.986,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    density: 2.7,
    state: "solid",
    discoveryYear: 1827,
    description: "Aluminum is a silvery-white, soft, non-magnetic, ductile metal. It has remarkable ability to resist corrosion.",
    uses: ["Construction", "Packaging", "Transportation"],
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition",
    group: 13,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    atomicRadius: 135,
    ionizationEnergy: 5.999,
    meltingPoint: 29.76,
    boilingPoint: 2400,
    density: 5.91,
    state: "solid",
    discoveryYear: 1875,
    description: "Gallium is a soft, silvery metal that becomes liquid at around 30°C, so it can melt in your hand. It has the longest liquid range of any metal.",
    uses: ["Semiconductors", "LEDs", "High-temperature thermometers"],
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.818,
    category: "post-transition",
    group: 13,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    atomicRadius: 155,
    ionizationEnergy: 5.786,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    density: 7.31,
    state: "solid",
    discoveryYear: 1863,
    description: "Indium is a soft, malleable post-transition metal with a bright luster. When bent, it emits a high-pitched 'cry'.",
    uses: ["Touchscreens", "Solders", "LCD displays"],
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.383,
    category: "post-transition",
    group: 13,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    atomicRadius: 190,
    ionizationEnergy: 6.108,
    meltingPoint: 304,
    boilingPoint: 1473,
    density: 11.85,
    state: "solid",
    discoveryYear: 1861,
    description: "Thallium is a soft, malleable gray metal with a bluish tinge when freshly cut. It is extremely toxic and was once used as rat poison.",
    uses: ["Electronics", "Glass manufacturing", "Medical imaging"],
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "unknown",
    group: 13,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹ (predicted)",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2004,
    description: "Nihonium is a synthetic element that does not occur naturally. It has only been produced in laboratories and is highly unstable.",
    uses: ["Scientific research"],
  },
  
  // Group 14 (IVA)
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    group: 14,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p²",
    electronegativity: 2.55,
    atomicRadius: 70,
    ionizationEnergy: 11.260,
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    state: "solid",
    discoveryYear: null,
    description: "Carbon is the basis of organic chemistry and life. It exists in various forms including diamond, graphite and fullerenes.",
    uses: ["Steel production", "Carbon fiber", "Fuel"],
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    group: 14,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    atomicRadius: 111,
    ionizationEnergy: 8.152,
    meltingPoint: 1414,
    boilingPoint: 3265,
    density: 2.33,
    state: "solid",
    discoveryYear: 1824,
    description: "Silicon is a hard and brittle crystalline solid with a blue-grey metallic luster. It is the second most abundant element in the Earth's crust.",
    uses: ["Semiconductors", "Solar cells", "Glass manufacturing"],
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.630,
    category: "metalloid",
    group: 14,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    atomicRadius: 125,
    ionizationEnergy: 7.899,
    meltingPoint: 938.25,
    boilingPoint: 2833,
    density: 5.323,
    state: "solid",
    discoveryYear: 1886,
    description: "Germanium is a lustrous, hard-brittle, grayish-white metalloid in the carbon group. It has properties of both metals and nonmetals.",
    uses: ["Fiber optics", "Infrared optics", "Polymerization catalysts"],
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.710,
    category: "post-transition",
    group: 14,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    atomicRadius: 145,
    ionizationEnergy: 7.344,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    density: 7.31,
    state: "solid",
    discoveryYear: null,
    description: "Tin is a silvery-white metal that is malleable and easily worked. It resists corrosion and is used to coat other metals to prevent corrosion.",
    uses: ["Food packaging", "Solder", "Bronze and pewter alloys"],
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition",
    group: 14,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    atomicRadius: 180,
    ionizationEnergy: 7.417,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    density: 11.34,
    state: "solid",
    discoveryYear: null,
    description: "Lead is a heavy, soft, malleable, bluish-gray metal. It is resistant to corrosion but tarnishes upon exposure to air.",
    uses: ["Batteries", "Radiation shielding", "Bullets and shot"],
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "unknown",
    group: 14,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p² (predicted)",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 1999,
    description: "Flerovium is a synthetic, superheavy element that doesn't occur naturally. Due to its extremely short half-life, only a few atoms have ever been produced.",
    uses: ["Scientific research"],
  },
  
  // Group 15 (VA)
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    group: 15,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p³",
    electronegativity: 3.04,
    atomicRadius: 65,
    ionizationEnergy: 14.534,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    density: 0.0012506,
    state: "gas",
    discoveryYear: 1772,
    description: "Nitrogen is a colorless, odorless, tasteless gas that makes up about 78% of Earth's atmosphere.",
    uses: ["Fertilizers", "Refrigerant", "Explosives manufacturing"],
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    group: 15,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 10.487,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    density: 1.82,
    state: "solid",
    discoveryYear: 1669,
    description: "Phosphorus exists in several forms (white, red, black) and is highly reactive. It is essential for life and is found in DNA and ATP.",
    uses: ["Fertilizers", "Detergents", "Match heads"],
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    group: 15,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    atomicRadius: 115,
    ionizationEnergy: 9.815,
    meltingPoint: 817,
    boilingPoint: 614,
    density: 5.727,
    state: "solid",
    discoveryYear: null,
    description: "Arsenic is a metalloid that occurs in many minerals. It's known for its toxicity and has been used as a poison throughout history.",
    uses: ["Semiconductors", "Wood preservatives", "Alloys"],
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.760,
    category: "metalloid",
    group: 15,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    atomicRadius: 145,
    ionizationEnergy: 8.64,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    density: 6.68,
    state: "solid",
    discoveryYear: null,
    description: "Antimony is a lustrous, silvery, bluish-white metalloid with poor heat and electrical conductivity. It is used in flame-proofing, batteries, and alloys.",
    uses: ["Flame retardants", "Batteries", "Type metal"],
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.980,
    category: "post-transition",
    group: 15,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    atomicRadius: 160,
    ionizationEnergy: 7.289,
    meltingPoint: 271.4,
    boilingPoint: 1564,
    density: 9.78,
    state: "solid",
    discoveryYear: 1753,
    description: "Bismuth is a brittle, crystalline, white metal with a pinkish tinge. It is the most naturally diamagnetic element and has one of the lowest thermal conductivities.",
    uses: ["Cosmetics", "Pharmaceuticals", "Low-melting alloys"],
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "unknown",
    group: 15,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³ (predicted)",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2004,
    description: "Moscovium is a synthetic element that has only been created in laboratories. Only a few atoms have ever been produced.",
    uses: ["Scientific research"],
  },
  
  // Group 16 (VIA)
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    group: 16,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    atomicRadius: 60,
    ionizationEnergy: 13.618,
    meltingPoint: -218.79,
    boilingPoint: -182.962,
    density: 0.001429,
    state: "gas",
    discoveryYear: 1774,
    description: "Oxygen is highly reactive and forms compounds with most elements. It is essential for respiration and makes up about 21% of Earth's atmosphere.",
    uses: ["Medical applications", "Steelmaking", "Rocket propellant"],
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    group: 16,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 10.36,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    density: 2.067,
    state: "solid",
    discoveryYear: null,
    description: "Sulfur is a bright yellow nonmetallic element. It is abundant, multivalent, and nonmetallic.",
    uses: ["Fertilizers", "Gunpowder", "Vulcanization of rubber"],
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    group: 16,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    atomicRadius: 103,
    ionizationEnergy: 9.752,
    meltingPoint: 221,
    boilingPoint: 685,
    density: 4.79,
    state: "solid",
    discoveryYear: 1817,
    description: "Selenium is a nonmetal with properties similar to sulfur and tellurium. It exists in several allotropic forms, including a red amorphous powder and a gray crystalline form.",
    uses: ["Electronics", "Glass manufacturing", "Nutritional supplements"],
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.60,
    category: "metalloid",
    group: 16,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    atomicRadius: 123,
    ionizationEnergy: 9.01,
    meltingPoint: 449.51,
    boilingPoint: 988,
    density: 6.24,
    state: "solid",
    discoveryYear: 1782,
    description: "Tellurium is a brittle, silvery-white metalloid with properties similar to both metals and nonmetals. When burned in air, it produces a greenish-blue flame and forms tellurium dioxide.",
    uses: ["Alloys", "Solar panels", "Rubber manufacturing"],
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "post-transition",
    group: 16,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    atomicRadius: 135,
    ionizationEnergy: 8.417,
    meltingPoint: 254,
    boilingPoint: 962,
    density: 9.32,
    state: "solid",
    discoveryYear: 1898,
    description: "Polonium is a rare, radioactive metal. It is extremely toxic and has no stable isotopes. It was discovered by Marie Curie, who named it after her native country Poland.",
    uses: ["Eliminating static electricity", "Space equipment heat sources", "Research"],
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "unknown",
    group: 16,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴ (predicted)",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2000,
    description: "Livermorium is a synthetic element that has only been produced in laboratories. It is highly unstable with a half-life of milliseconds.",
    uses: ["Scientific research"],
  },
  
  // Group 17 (VIIA): Halogens
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "nonmetal",
    group: 17,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    atomicRadius: 50,
    ionizationEnergy: 17.423,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    density: 0.001696,
    state: "gas",
    discoveryYear: 1886,
    description: "Fluorine is the most electronegative and reactive of all elements. It reacts with almost all organic and inorganic substances.",
    uses: ["Toothpaste", "Refrigerants", "Nuclear fuel processing"],
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "nonmetal",
    group: 17,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 12.968,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    density: 0.003214,
    state: "gas",
    discoveryYear: 1774,
    description: "Chlorine is a greenish-yellow gas which combines with most elements. It is widely used for water purification.",
    uses: ["Water purification", "Disinfectants", "PVC production"],
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "nonmetal",
    group: 17,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    atomicRadius: 94,
    ionizationEnergy: 11.814,
    meltingPoint: -7.3,
    boilingPoint: 58.8,
    density: 3.1028,
    state: "liquid",
    discoveryYear: 1826,
    description: "Bromine is a reddish-brown liquid at room temperature that evaporates readily to form a similarly colored gas. It is the only nonmetallic element that is liquid at room temperature.",
    uses: ["Flame retardants", "Water purification", "Photography"],
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.904,
    category: "nonmetal",
    group: 17,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    atomicRadius: 115,
    ionizationEnergy: 10.451,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    density: 4.933,
    state: "solid",
    discoveryYear: 1811,
    description: "Iodine is a dark purple-black solid that sublimes into a violet gas. It is the heaviest essential mineral nutrient, required for thyroid hormone production.",
    uses: ["Antiseptics", "Photography", "Nutritional supplements"],
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "nonmetal",
    group: 17,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    atomicRadius: 127,
    ionizationEnergy: 9.75,
    meltingPoint: 302,
    boilingPoint: 337,
    density: null,
    state: "solid",
    discoveryYear: 1940,
    description: "Astatine is the rarest naturally occurring element in the Earth's crust. It is highly radioactive, and its properties are not well known due to its instability.",
    uses: ["Medical research", "Cancer treatment research"],
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "unknown",
    group: 17,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵ (predicted)",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2010,
    description: "Tennessine is a synthetic element with the second-highest atomic number of any element that has been produced. Only a few atoms have ever been created.",
    uses: ["Scientific research"],
  },
];
