
import { Element } from '../constants';

export const metalloids: Element[] = [
  {
    atomicNumber: 5,
    symbol: "B",
    name: "Boron",
    atomicMass: 10.81,
    category: "metalloid",
    group: 13,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p¹",
    electronegativity: 2.04,
    atomicRadius: 85,
    ionizationEnergy: 8.298,
    meltingPoint: 2076,
    boilingPoint: 3927,
    density: 2.34,
    state: "solid",
    discoveryYear: 1808,
    description: "Boron is a semiconductor with properties between metals and non-metals. It is never found free in nature.",
    uses: ["Glass manufacturing", "Detergents", "Agriculture"],
  },
  {
    atomicNumber: 14,
    symbol: "Si",
    name: "Silicon",
    atomicMass: 28.085,
    category: "metalloid",
    group: 14,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p²",
    electronegativity: 1.9,
    atomicRadius: 111,
    ionizationEnergy: 8.152,
    meltingPoint: 1414,
    boilingPoint: 3265,
    density: 2.33,
    state: "solid",
    discoveryYear: 1824,
    description: "Silicon is a hard and brittle crystalline solid with a blue-grey metallic luster. It is the second most abundant element in the Earth's crust.",
    uses: ["Semiconductors", "Solar cells", "Glass manufacturing"],
  },
  {
    atomicNumber: 32,
    symbol: "Ge",
    name: "Germanium",
    atomicMass: 72.630,
    category: "metalloid",
    group: 14,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: 2.01,
    atomicRadius: 122,
    ionizationEnergy: 7.900,
    meltingPoint: 938.25,
    boilingPoint: 2833,
    density: 5.323,
    state: "solid",
    discoveryYear: 1886,
    description: "Germanium is a lustrous, hard, grayish-white metalloid. It is primarily used in semiconductor devices.",
    uses: ["Fiber optics", "Infrared optics", "Polymerization catalysts"],
  },
  {
    atomicNumber: 33,
    symbol: "As",
    name: "Arsenic",
    atomicMass: 74.922,
    category: "metalloid",
    group: 15,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: 2.18,
    atomicRadius: 119,
    ionizationEnergy: 9.815,
    meltingPoint: 816,
    boilingPoint: 614,
    density: 5.727,
    state: "solid",
    discoveryYear: null,
    description: "Arsenic is a notoriously poisonous metalloid that has three allotropic forms: yellow, black, and gray. Gray is the most common form.",
    uses: ["Wood preservatives", "Alloys", "Semiconductors"],
  },
  {
    atomicNumber: 51,
    symbol: "Sb",
    name: "Antimony",
    atomicMass: 121.76,
    category: "metalloid",
    group: 15,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: 2.05,
    atomicRadius: 140,
    ionizationEnergy: 8.641,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    density: 6.68,
    state: "solid",
    discoveryYear: null,
    description: "Antimony is a lustrous gray metalloid with a Mohs scale hardness of 3. It is stable in air and unaffected by alkalis and most acids.",
    uses: ["Flame retardants", "Batteries", "Alloys"],
  },
  {
    atomicNumber: 52,
    symbol: "Te",
    name: "Tellurium",
    atomicMass: 127.6,
    category: "metalloid",
    group: 16,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: 2.1,
    atomicRadius: 142,
    ionizationEnergy: 9.010,
    meltingPoint: 449.51,
    boilingPoint: 988,
    density: 6.24,
    state: "solid",
    discoveryYear: 1782,
    description: "Tellurium is a brittle, mildly toxic, rare, silver-white metalloid. It is chemically related to selenium and sulfur.",
    uses: ["Solar panels", "Thermoelectric materials", "Alloys"],
  },
  {
    atomicNumber: 85,
    symbol: "At",
    name: "Astatine",
    atomicMass: 210,
    category: "metalloid",
    group: 17,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: 2.2,
    atomicRadius: 150,
    ionizationEnergy: 9.32,
    meltingPoint: 302,
    boilingPoint: 337,
    density: null,
    state: "solid",
    discoveryYear: 1940,
    description: "Astatine is a radioactive element with no stable isotopes. It is the rarest naturally occurring element in the Earth's crust.",
    uses: ["Nuclear medicine (potential)", "Scientific research"],
  }
];
