
import { Element } from '../constants';

export const nobleGases: Element[] = [
  {
    atomicNumber: 2,
    symbol: "He",
    name: "Helium",
    atomicMass: 4.0026,
    category: "noble-gas",
    group: 18,
    period: 1,
    block: "s",
    electronConfiguration: "1s²",
    electronegativity: null,
    atomicRadius: 32,
    ionizationEnergy: 24.587,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    density: 0.0001785,
    state: "gas",
    discoveryYear: 1868,
    description: "Helium is the second lightest and second most abundant element in the universe. It is colorless, odorless, tasteless, and inert.",
    uses: ["Balloons", "Cryogenics", "Cooling MRI magnets"],
  },
  {
    atomicNumber: 10,
    symbol: "Ne",
    name: "Neon",
    atomicMass: 20.180,
    category: "noble-gas",
    group: 18,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁶",
    electronegativity: null,
    atomicRadius: 38,
    ionizationEnergy: 21.565,
    meltingPoint: -248.59,
    boilingPoint: -246.046,
    density: 0.0008999,
    state: "gas",
    discoveryYear: 1898,
    description: "Neon is an inert noble gas that gives a distinctive reddish-orange glow when used in low-voltage gas-discharge lamps.",
    uses: ["Neon signs", "Refrigerant", "Lasers"],
  },
  {
    atomicNumber: 18,
    symbol: "Ar",
    name: "Argon",
    atomicMass: 39.95,
    category: "noble-gas",
    group: 18,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    electronegativity: null,
    atomicRadius: 71,
    ionizationEnergy: 15.76,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    density: 0.0017837,
    state: "gas",
    discoveryYear: 1894,
    description: "Argon is a colorless, odorless noble gas. It makes up almost 1% of the Earth's atmosphere.",
    uses: ["Light bulbs", "Welding", "Growing silicon crystals"],
  },
  {
    atomicNumber: 36,
    symbol: "Kr",
    name: "Krypton",
    atomicMass: 83.798,
    category: "noble-gas",
    group: 18,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: 3.0,
    atomicRadius: 88,
    ionizationEnergy: 14.000,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    density: 0.003733,
    state: "gas",
    discoveryYear: 1898,
    description: "Krypton is a colorless, odorless, tasteless noble gas. It is used in some types of photographic flashes and fluorescent lights.",
    uses: ["Lighting", "Lasers", "Window insulation"],
  },
  {
    atomicNumber: 54,
    symbol: "Xe",
    name: "Xenon",
    atomicMass: 131.29,
    category: "noble-gas",
    group: 18,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: 2.6,
    atomicRadius: 108,
    ionizationEnergy: 12.130,
    meltingPoint: -111.8,
    boilingPoint: -108.1,
    density: 0.00588,
    state: "gas",
    discoveryYear: 1898,
    description: "Xenon is a colorless, dense, odorless noble gas. It can form some compounds, unlike lighter noble gases.",
    uses: ["High-intensity lamps", "Medical imaging", "Space propulsion"],
  },
  {
    atomicNumber: 86,
    symbol: "Rn",
    name: "Radon",
    atomicMass: 222,
    category: "noble-gas",
    group: 18,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: 2.2,
    atomicRadius: 120,
    ionizationEnergy: 10.745,
    meltingPoint: -71,
    boilingPoint: -61.7,
    density: 0.00973,
    state: "gas",
    discoveryYear: 1900,
    description: "Radon is a radioactive, colorless, odorless, tasteless noble gas. It is produced by the natural decay of uranium.",
    uses: ["Cancer treatment", "Geologic research", "Indoor air quality monitoring"],
  },
  {
    atomicNumber: 118,
    symbol: "Og",
    name: "Oganesson",
    atomicMass: 294,
    category: "noble-gas",
    group: 18,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2002,
    description: "Oganesson is a synthetic element and is the heaviest element created so far. Due to its radioactivity and short half-life, its properties are not well-studied.",
    uses: ["Scientific research"],
  }
];
