import { Element } from '../constants';

export const nonmetals: Element[] = [
  {
    atomicNumber: 1,
    symbol: "H",
    name: "Hydrogen",
    atomicMass: 1.008,
    category: "nonmetal",
    group: 1,
    period: 1,
    block: "s",
    electronConfiguration: "1s¹",
    electronegativity: 2.2,
    atomicRadius: 38,
    ionizationEnergy: 13.598,
    meltingPoint: -259.16,
    boilingPoint: -252.879,
    density: 0.00008988,
    state: "gas",
    discoveryYear: 1766,
    description: "Hydrogen is the lightest and most abundant element in the universe. It is present in water and in all organic compounds.",
    uses: ["Fuel", "Making ammonia", "Hydrogenation of oils to make fats"],
  },
  {
    atomicNumber: 6,
    symbol: "C",
    name: "Carbon",
    atomicMass: 12.011,
    category: "nonmetal",
    group: 14,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p²",
    electronegativity: 2.55,
    atomicRadius: 70,
    ionizationEnergy: 11.260,
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    state: "solid",
    discoveryYear: null,
    description: "Carbon is the basis of organic chemistry and life. It exists in various forms including diamond, graphite and fullerenes.",
    uses: ["Steel production", "Carbon fiber", "Fuel"],
  },
  {
    atomicNumber: 7,
    symbol: "N",
    name: "Nitrogen",
    atomicMass: 14.007,
    category: "nonmetal",
    group: 15,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p³",
    electronegativity: 3.04,
    atomicRadius: 65,
    ionizationEnergy: 14.534,
    meltingPoint: -210.1,
    boilingPoint: -195.79,
    density: 0.0012506,
    state: "gas",
    discoveryYear: 1772,
    description: "Nitrogen is a colorless, odorless, tasteless gas that makes up about 78% of Earth's atmosphere.",
    uses: ["Fertilizers", "Refrigerant", "Explosives manufacturing"],
  },
  {
    atomicNumber: 8,
    symbol: "O",
    name: "Oxygen",
    atomicMass: 15.999,
    category: "nonmetal",
    group: 16,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁴",
    electronegativity: 3.44,
    atomicRadius: 60,
    ionizationEnergy: 13.618,
    meltingPoint: -218.79,
    boilingPoint: -182.962,
    density: 0.001429,
    state: "gas",
    discoveryYear: 1774,
    description: "Oxygen is highly reactive and forms compounds with most elements. It is essential for respiration and makes up about 21% of Earth's atmosphere.",
    uses: ["Medical applications", "Steelmaking", "Rocket propellant"],
  },
  {
    atomicNumber: 9,
    symbol: "F",
    name: "Fluorine",
    atomicMass: 18.998,
    category: "nonmetal",
    group: 17,
    period: 2,
    block: "p",
    electronConfiguration: "[He] 2s² 2p⁵",
    electronegativity: 3.98,
    atomicRadius: 50,
    ionizationEnergy: 17.423,
    meltingPoint: -219.67,
    boilingPoint: -188.11,
    density: 0.001696,
    state: "gas",
    discoveryYear: 1886,
    description: "Fluorine is the most electronegative and reactive of all elements. It reacts with almost all organic and inorganic substances.",
    uses: ["Toothpaste", "Refrigerants", "Nuclear fuel processing"],
  },
  {
    atomicNumber: 15,
    symbol: "P",
    name: "Phosphorus",
    atomicMass: 30.974,
    category: "nonmetal",
    group: 15,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p³",
    electronegativity: 2.19,
    atomicRadius: 98,
    ionizationEnergy: 10.487,
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    density: 1.82,
    state: "solid",
    discoveryYear: 1669,
    description: "Phosphorus exists in several forms (white, red, black) and is highly reactive. It is essential for life and is found in DNA and ATP.",
    uses: ["Fertilizers", "Detergents", "Match heads"],
  },
  {
    atomicNumber: 16,
    symbol: "S",
    name: "Sulfur",
    atomicMass: 32.06,
    category: "nonmetal",
    group: 16,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    electronegativity: 2.58,
    atomicRadius: 88,
    ionizationEnergy: 10.36,
    meltingPoint: 115.21,
    boilingPoint: 444.6,
    density: 2.067,
    state: "solid",
    discoveryYear: null,
    description: "Sulfur is a bright yellow nonmetallic element. It is abundant, multivalent, and nonmetallic.",
    uses: ["Fertilizers", "Gunpowder", "Vulcanization of rubber"],
  },
  {
    atomicNumber: 17,
    symbol: "Cl",
    name: "Chlorine",
    atomicMass: 35.45,
    category: "nonmetal",
    group: 17,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    electronegativity: 3.16,
    atomicRadius: 79,
    ionizationEnergy: 12.968,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    density: 0.003214,
    state: "gas",
    discoveryYear: 1774,
    description: "Chlorine is a greenish-yellow gas which combines with most elements. It is widely used for water purification.",
    uses: ["Water purification", "Disinfectants", "PVC production"],
  },
  {
    atomicNumber: 34,
    symbol: "Se",
    name: "Selenium",
    atomicMass: 78.971,
    category: "nonmetal",
    group: 16,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: 2.55,
    atomicRadius: 120,
    ionizationEnergy: 9.752,
    meltingPoint: 221,
    boilingPoint: 685,
    density: 4.809,
    state: "solid",
    discoveryYear: 1817,
    description: "Selenium is a non-metal with properties of both metals and non-metals. It exists in several allotropic forms.",
    uses: ["Solar cells", "Photocopiers", "Nutritional supplements"],
  },
  {
    atomicNumber: 35,
    symbol: "Br",
    name: "Bromine",
    atomicMass: 79.904,
    category: "nonmetal",
    group: 17,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: 2.96,
    atomicRadius: 120,
    ionizationEnergy: 11.814,
    meltingPoint: -7.3,
    boilingPoint: 58.8,
    density: 3.11,
    state: "liquid",
    discoveryYear: 1826,
    description: "Bromine is a reddish-brown liquid at room temperature with a strong odor. It is the only nonmetallic element that is liquid at room temperature.",
    uses: ["Flame retardants", "Water purification", "Photography"],
  },
  {
    atomicNumber: 53,
    symbol: "I",
    name: "Iodine",
    atomicMass: 126.90,
    category: "nonmetal",
    group: 17,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: 2.66,
    atomicRadius: 140,
    ionizationEnergy: 10.451,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    density: 4.93,
    state: "solid",
    discoveryYear: 1811,
    description: "Iodine is a bluish-black, lustrous solid that sublimes to a violet gas. It is the heaviest of the stable halogens and is primarily used in medicine and photography.",
    uses: ["Disinfectants", "Photography", "Nutritional supplements"],
  },
  {
    atomicNumber: 117,
    symbol: "Ts",
    name: "Tennessine",
    atomicMass: 294,
    category: "nonmetal",
    group: 17,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2010,
    description: "Tennessine is a synthetic element named after the state of Tennessee. Only a few atoms have ever been produced, and its chemical properties are not well-studied.",
    uses: ["Scientific research"],
  }
];
