import { Element } from '../constants';

export const postTransitionMetals: Element[] = [
  {
    atomicNumber: 13,
    symbol: "Al",
    name: "Aluminum",
    atomicMass: 26.982,
    category: "post-transition",
    group: 13,
    period: 3,
    block: "p",
    electronConfiguration: "[Ne] 3s² 3p¹",
    electronegativity: 1.61,
    atomicRadius: 143,
    ionizationEnergy: 5.986,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    density: 2.7,
    state: "solid",
    discoveryYear: 1827,
    description: "Aluminum is a silvery-white, soft, non-magnetic, ductile metal. It has remarkable ability to resist corrosion.",
    uses: ["Construction", "Packaging", "Transportation"],
  },
  {
    atomicNumber: 31,
    symbol: "Ga",
    name: "Gallium",
    atomicMass: 69.723,
    category: "post-transition",
    group: 13,
    period: 4,
    block: "p",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: 1.81,
    atomicRadius: 135,
    ionizationEnergy: 5.999,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    density: 5.91,
    state: "solid",
    discoveryYear: 1875,
    description: "Gallium is a soft, silvery metal that becomes liquid at around 30°C, just above room temperature. It can wet glass and similar surfaces.",
    uses: ["Semiconductors", "LEDs", "High-temperature thermometers"],
  },
  {
    atomicNumber: 49,
    symbol: "In",
    name: "Indium",
    atomicMass: 114.818,
    category: "post-transition",
    group: 13,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: 1.78,
    atomicRadius: 156,
    ionizationEnergy: 5.786,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    density: 7.31,
    state: "solid",
    discoveryYear: 1863,
    description: "Indium is a soft, malleable, and easily fusible post-transition metal. It is liquid over a wide range of temperatures and has a bright luster.",
    uses: ["Touch screens", "Solders", "LCD displays"],
  },
  {
    atomicNumber: 50,
    symbol: "Sn",
    name: "Tin",
    atomicMass: 118.71,
    category: "post-transition",
    group: 14,
    period: 5,
    block: "p",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: 1.96,
    atomicRadius: 145,
    ionizationEnergy: 7.344,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    density: 7.265,
    state: "solid",
    discoveryYear: null,
    description: "Tin is a silvery metal that characteristically has a faint yellow hue. It is malleable, ductile, and highly crystalline.",
    uses: ["Solder", "Food packaging", "Glass manufacturing"],
  },
  {
    atomicNumber: 81,
    symbol: "Tl",
    name: "Thallium",
    atomicMass: 204.38,
    category: "post-transition",
    group: 13,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: 1.62,
    atomicRadius: 170,
    ionizationEnergy: 6.108,
    meltingPoint: 304,
    boilingPoint: 1473,
    density: 11.85,
    state: "solid",
    discoveryYear: 1861,
    description: "Thallium is a soft, malleable gray metal that is highly toxic. It tarnishes quickly in air forming a bluish-gray layer of oxide.",
    uses: ["Electronics", "Specialized glass", "Medical imaging"],
  },
  {
    atomicNumber: 82,
    symbol: "Pb",
    name: "Lead",
    atomicMass: 207.2,
    category: "post-transition",
    group: 14,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: 1.87,
    atomicRadius: 175,
    ionizationEnergy: 7.417,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    density: 11.34,
    state: "solid",
    discoveryYear: null,
    description: "Lead is a soft, malleable, and heavy metal with a bluish-white color when freshly cut, but it tarnishes to a dull grayish color when exposed to air.",
    uses: ["Batteries", "Radiation shielding", "Construction materials"],
  },
  {
    atomicNumber: 83,
    symbol: "Bi",
    name: "Bismuth",
    atomicMass: 208.98,
    category: "post-transition",
    group: 15,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: 2.02,
    atomicRadius: 160,
    ionizationEnergy: 7.289,
    meltingPoint: 271.3,
    boilingPoint: 1564,
    density: 9.78,
    state: "solid",
    discoveryYear: null,
    description: "Bismuth is a brittle, crystalline, white metal with a pinkish tinge. It has one of the lowest thermal conductivities among metals.",
    uses: ["Pharmaceuticals", "Cosmetics", "Alloys with low melting points"],
  },
  {
    atomicNumber: 84,
    symbol: "Po",
    name: "Polonium",
    atomicMass: 209,
    category: "post-transition",
    group: 16,
    period: 6,
    block: "p",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: 2.0,
    atomicRadius: 168,
    ionizationEnergy: 8.417,
    meltingPoint: 254,
    boilingPoint: 962,
    density: 9.32,
    state: "solid",
    discoveryYear: 1898,
    description: "Polonium is a rare and highly radioactive metal. It is chemically similar to tellurium and bismuth and is found in uranium ores.",
    uses: ["Anti-static devices", "Thermoelectric power sources", "Space equipment heat source"],
  },
  {
    atomicNumber: 113,
    symbol: "Nh",
    name: "Nihonium",
    atomicMass: 286,
    category: "post-transition",
    group: 13,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2004,
    description: "Nihonium is a synthetic element with a very short half-life. It has only been produced in small amounts, so its properties are largely unknown.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 114,
    symbol: "Fl",
    name: "Flerovium",
    atomicMass: 289,
    category: "post-transition",
    group: 14,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 1999,
    description: "Flerovium is a superheavy artificial element that has been created in a laboratory. It may be more noble-gas-like in its chemical properties than lead.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 115,
    symbol: "Mc",
    name: "Moscovium",
    atomicMass: 290,
    category: "post-transition",
    group: 15,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2003,
    description: "Moscovium is a synthetic element named after Moscow Oblast in Russia. It is extremely radioactive, and only a few atoms have ever been produced.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 116,
    symbol: "Lv",
    name: "Livermorium",
    atomicMass: 293,
    category: "post-transition",
    group: 16,
    period: 7,
    block: "p",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "unknown",
    discoveryYear: 2000,
    description: "Livermorium is a synthetic element named after the Lawrence Livermore National Laboratory. It is extremely radioactive and unstable.",
    uses: ["Scientific research"],
  }
];
