
import { Element } from '../constants';

export const transitionMetals: Element[] = [
  {
    atomicNumber: 21,
    symbol: "Sc",
    name: "Scandium",
    atomicMass: 44.956,
    category: "transition-metal",
    group: 3,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹ 4s²",
    electronegativity: 1.36,
    atomicRadius: 162,
    ionizationEnergy: 6.561,
    meltingPoint: 1541,
    boilingPoint: 2836,
    density: 2.989,
    state: "solid",
    discoveryYear: 1879,
    description: "Scandium is a silvery-white metal that becomes yellowish or pinkish in air. It is relatively soft and lightweight.",
    uses: ["Aluminum alloys", "Sports equipment", "Lighting"],
  },
  {
    atomicNumber: 22,
    symbol: "Ti",
    name: "Titanium",
    atomicMass: 47.867,
    category: "transition-metal",
    group: 4,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d² 4s²",
    electronegativity: 1.54,
    atomicRadius: 147,
    ionizationEnergy: 6.828,
    meltingPoint: 1668,
    boilingPoint: 3287,
    density: 4.54,
    state: "solid",
    discoveryYear: 1791,
    description: "Titanium is a strong, lightweight, corrosion-resistant metal with a silver color. It has the highest strength-to-density ratio of any metallic element.",
    uses: ["Aerospace", "Medical implants", "Consumer electronics"],
  },
  {
    atomicNumber: 23,
    symbol: "V",
    name: "Vanadium",
    atomicMass: 50.942,
    category: "transition-metal",
    group: 5,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d³ 4s²",
    electronegativity: 1.63,
    atomicRadius: 134,
    ionizationEnergy: 6.746,
    meltingPoint: 1910,
    boilingPoint: 3407,
    density: 6.11,
    state: "solid",
    discoveryYear: 1801,
    description: "Vanadium is a silvery-gray metal that is ductile, malleable, and resistant to corrosion. It naturally occurs in about 65 minerals.",
    uses: ["Steel additives", "Aerospace", "Chemical catalyst"],
  },
  {
    atomicNumber: 24,
    symbol: "Cr",
    name: "Chromium",
    atomicMass: 51.996,
    category: "transition-metal",
    group: 6,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    electronegativity: 1.66,
    atomicRadius: 128,
    ionizationEnergy: 6.767,
    meltingPoint: 1907,
    boilingPoint: 2671,
    density: 7.15,
    state: "solid",
    discoveryYear: 1797,
    description: "Chromium is a steely-gray, lustrous, hard metal that takes a high polish and has a high melting point. It is also odorless, tasteless, and malleable.",
    uses: ["Stainless steel", "Chrome plating", "Dyes and pigments"],
  },
  {
    atomicNumber: 25,
    symbol: "Mn",
    name: "Manganese",
    atomicMass: 54.938,
    category: "transition-metal",
    group: 7,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    electronegativity: 1.55,
    atomicRadius: 127,
    ionizationEnergy: 7.434,
    meltingPoint: 1246,
    boilingPoint: 2061,
    density: 7.44,
    state: "solid",
    discoveryYear: 1774,
    description: "Manganese is a silvery-gray metal that resembles iron. It is hard and very brittle, difficult to fuse, but easy to oxidize.",
    uses: ["Steel production", "Batteries", "Aluminum cans"],
  },
  {
    atomicNumber: 26,
    symbol: "Fe",
    name: "Iron",
    atomicMass: 55.845,
    category: "transition-metal",
    group: 8,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    electronegativity: 1.83,
    atomicRadius: 126,
    ionizationEnergy: 7.902,
    meltingPoint: 1538,
    boilingPoint: 2861,
    density: 7.874,
    state: "solid",
    discoveryYear: null,
    description: "Iron is a silvery-white, lustrous metal that is very ductile and malleable. It is the most common element on Earth by mass and the most widely used metal.",
    uses: ["Steel production", "Construction", "Tools and machinery"],
  },
  {
    atomicNumber: 27,
    symbol: "Co",
    name: "Cobalt",
    atomicMass: 58.933,
    category: "transition-metal",
    group: 9,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    electronegativity: 1.88,
    atomicRadius: 125,
    ionizationEnergy: 7.881,
    meltingPoint: 1495,
    boilingPoint: 2927,
    density: 8.86,
    state: "solid",
    discoveryYear: 1735,
    description: "Cobalt is a hard, lustrous, silver-gray metal. It is found in the Earth's crust only in chemically combined form.",
    uses: ["Batteries", "Superalloys", "Magnets"],
  },
  {
    atomicNumber: 28,
    symbol: "Ni",
    name: "Nickel",
    atomicMass: 58.693,
    category: "transition-metal",
    group: 10,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    electronegativity: 1.91,
    atomicRadius: 124,
    ionizationEnergy: 7.640,
    meltingPoint: 1455,
    boilingPoint: 2913,
    density: 8.912,
    state: "solid",
    discoveryYear: 1751,
    description: "Nickel is a silvery-white metal with a slight golden tinge. It is hard, ductile, malleable, and a fair conductor of heat and electricity.",
    uses: ["Stainless steel", "Batteries", "Coins"],
  },
  {
    atomicNumber: 29,
    symbol: "Cu",
    name: "Copper",
    atomicMass: 63.546,
    category: "transition-metal",
    group: 11,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: 1.9,
    atomicRadius: 128,
    ionizationEnergy: 7.726,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    density: 8.96,
    state: "solid",
    discoveryYear: null,
    description: "Copper is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. It has a characteristic reddish-orange color.",
    uses: ["Electrical wiring", "Plumbing", "Roofing"],
  },
  {
    atomicNumber: 30,
    symbol: "Zn",
    name: "Zinc",
    atomicMass: 65.38,
    category: "transition-metal",
    group: 12,
    period: 4,
    block: "d",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    electronegativity: 1.65,
    atomicRadius: 134,
    ionizationEnergy: 9.394,
    meltingPoint: 419.53,
    boilingPoint: 907,
    density: 7.14,
    state: "solid",
    discoveryYear: 1746,
    description: "Zinc is a bluish-white, lustrous, diamagnetic metal. It is brittle at ambient temperatures but malleable at 100 to 150°C.",
    uses: ["Galvanization", "Brass alloys", "Batteries"],
  },
  {
    atomicNumber: 39,
    symbol: "Y",
    name: "Yttrium",
    atomicMass: 88.906,
    category: "transition-metal",
    group: 3,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹ 5s²",
    electronegativity: 1.22,
    atomicRadius: 180,
    ionizationEnergy: 6.217,
    meltingPoint: 1526,
    boilingPoint: 3336,
    density: 4.47,
    state: "solid",
    discoveryYear: 1794,
    description: "Yttrium is a silvery-metallic transition metal that is relatively stable in air. It's often found in combination with lanthanide elements in rare-earth minerals.",
    uses: ["LED phosphors", "Superconductors", "Cancer treatments"],
  },
  {
    atomicNumber: 40,
    symbol: "Zr",
    name: "Zirconium",
    atomicMass: 91.224,
    category: "transition-metal",
    group: 4,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d² 5s²",
    electronegativity: 1.33,
    atomicRadius: 160,
    ionizationEnergy: 6.634,
    meltingPoint: 1855,
    boilingPoint: 4409,
    density: 6.52,
    state: "solid",
    discoveryYear: 1789,
    description: "Zirconium is a lustrous, gray-white, strong transition metal that resembles hafnium and titanium. It is highly resistant to corrosion.",
    uses: ["Nuclear reactors", "Ceramics", "Flash bulbs"],
  },
  {
    atomicNumber: 41,
    symbol: "Nb",
    name: "Niobium",
    atomicMass: 92.906,
    category: "transition-metal",
    group: 5,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    electronegativity: 1.6,
    atomicRadius: 146,
    ionizationEnergy: 6.759,
    meltingPoint: 2477,
    boilingPoint: 4744,
    density: 8.57,
    state: "solid",
    discoveryYear: 1801,
    description: "Niobium is a shiny, white, soft, and ductile transition metal. It has excellent corrosion resistance and a high melting point.",
    uses: ["Steel alloys", "Superconducting magnets", "Jewelry"],
  },
  {
    atomicNumber: 42,
    symbol: "Mo",
    name: "Molybdenum",
    atomicMass: 95.95,
    category: "transition-metal",
    group: 6,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    electronegativity: 2.16,
    atomicRadius: 139,
    ionizationEnergy: 7.092,
    meltingPoint: 2623,
    boilingPoint: 4639,
    density: 10.28,
    state: "solid",
    discoveryYear: 1778,
    description: "Molybdenum is a silvery-white, hard transition metal. It has one of the highest melting points of all pure elements and is highly resistant to corrosion.",
    uses: ["High-strength steel alloys", "Catalysts", "Lubricants"],
  },
  {
    atomicNumber: 43,
    symbol: "Tc",
    name: "Technetium",
    atomicMass: 98,
    category: "transition-metal",
    group: 7,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    electronegativity: 1.9,
    atomicRadius: 136,
    ionizationEnergy: 7.28,
    meltingPoint: 2157,
    boilingPoint: 4265,
    density: 11.5,
    state: "solid",
    discoveryYear: 1937,
    description: "Technetium is a silvery-gray radioactive metal that tarnishes slowly in moist air. It is the lightest element whose isotopes are all radioactive.",
    uses: ["Medical diagnostics", "Nuclear medicine", "Corrosion inhibitors"],
  },
  {
    atomicNumber: 44,
    symbol: "Ru",
    name: "Ruthenium",
    atomicMass: 101.07,
    category: "transition-metal",
    group: 8,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    electronegativity: 2.2,
    atomicRadius: 134,
    ionizationEnergy: 7.361,
    meltingPoint: 2334,
    boilingPoint: 4150,
    density: 12.37,
    state: "solid",
    discoveryYear: 1844,
    description: "Ruthenium is a rare transition metal belonging to the platinum group. It is a hard, silvery-white metal that doesn't tarnish at room temperature.",
    uses: ["Electrical contacts", "Jewelry", "Catalytic converters"],
  },
  {
    atomicNumber: 45,
    symbol: "Rh",
    name: "Rhodium",
    atomicMass: 102.91,
    category: "transition-metal",
    group: 9,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    electronegativity: 2.28,
    atomicRadius: 134,
    ionizationEnergy: 7.459,
    meltingPoint: 1964,
    boilingPoint: 3695,
    density: 12.41,
    state: "solid",
    discoveryYear: 1803,
    description: "Rhodium is a rare, silvery-white, hard, corrosion-resistant transition metal. It is one of the rarest and most valuable precious metals.",
    uses: ["Catalytic converters", "Jewelry", "Lab equipment"],
  },
  {
    atomicNumber: 46,
    symbol: "Pd",
    name: "Palladium",
    atomicMass: 106.42,
    category: "transition-metal",
    group: 10,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰",
    electronegativity: 2.2,
    atomicRadius: 137,
    ionizationEnergy: 8.337,
    meltingPoint: 1555,
    boilingPoint: 2963,
    density: 12.02,
    state: "solid",
    discoveryYear: 1803,
    description: "Palladium is a rare and lustrous silvery-white metal. It has the lowest melting point and is the least dense of the platinum group metals.",
    uses: ["Catalytic converters", "Electronics", "Jewelry"],
  },
  {
    atomicNumber: 47,
    symbol: "Ag",
    name: "Silver",
    atomicMass: 107.87,
    category: "transition-metal",
    group: 11,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: 1.93,
    atomicRadius: 144,
    ionizationEnergy: 7.576,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    density: 10.49,
    state: "solid",
    discoveryYear: null,
    description: "Silver is a soft, white, lustrous transition metal with the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.",
    uses: ["Jewelry", "Photography", "Electrical contacts"],
  },
  {
    atomicNumber: 48,
    symbol: "Cd",
    name: "Cadmium",
    atomicMass: 112.41,
    category: "transition-metal",
    group: 12,
    period: 5,
    block: "d",
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    electronegativity: 1.69,
    atomicRadius: 151,
    ionizationEnergy: 8.994,
    meltingPoint: 321.07,
    boilingPoint: 767,
    density: 8.65,
    state: "solid",
    discoveryYear: 1817,
    description: "Cadmium is a soft, malleable, ductile, bluish-white metal with chemical properties similar to zinc. It is toxic and has few applications outside of specialized uses.",
    uses: ["Batteries", "Pigments", "Electroplating"],
  },
  {
    atomicNumber: 72,
    symbol: "Hf",
    name: "Hafnium",
    atomicMass: 178.49,
    category: "transition-metal",
    group: 4,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: 1.3,
    atomicRadius: 159,
    ionizationEnergy: 6.825,
    meltingPoint: 2233,
    boilingPoint: 4603,
    density: 13.31,
    state: "solid",
    discoveryYear: 1923,
    description: "Hafnium is a lustrous, silvery gray, tetravalent transition metal with excellent mechanical properties and high corrosion resistance.",
    uses: ["Nuclear reactors", "Superalloys", "Plasma cutting tips"],
  },
  {
    atomicNumber: 73,
    symbol: "Ta",
    name: "Tantalum",
    atomicMass: 180.95,
    category: "transition-metal",
    group: 5,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: 1.5,
    atomicRadius: 146,
    ionizationEnergy: 7.89,
    meltingPoint: 3017,
    boilingPoint: 5458,
    density: 16.69,
    state: "solid",
    discoveryYear: 1802,
    description: "Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant. It is part of the refractory metals group.",
    uses: ["Electronic components", "Surgical implants", "Cutting tools"],
  },
  {
    atomicNumber: 74,
    symbol: "W",
    name: "Tungsten",
    atomicMass: 183.84,
    category: "transition-metal",
    group: 6,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: 2.36,
    atomicRadius: 139,
    ionizationEnergy: 7.98,
    meltingPoint: 3422,
    boilingPoint: 5930,
    density: 19.25,
    state: "solid",
    discoveryYear: 1783,
    description: "Tungsten is a rare metal with exceptional properties: it has the highest melting point of all elements, excellent high-temperature strength, and high density.",
    uses: ["Filaments", "Alloys", "Military applications"],
  },
  {
    atomicNumber: 75,
    symbol: "Re",
    name: "Rhenium",
    atomicMass: 186.21,
    category: "transition-metal",
    group: 7,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: 1.9,
    atomicRadius: 137,
    ionizationEnergy: 7.88,
    meltingPoint: 3186,
    boilingPoint: 5596,
    density: 21.02,
    state: "solid",
    discoveryYear: 1925,
    description: "Rhenium is a silvery-white, heavy, third-row transition metal with one of the highest melting points of all elements. It resembles manganese and is resistant to corrosion.",
    uses: ["Superalloys", "Catalysts", "Electrical contacts"],
  },
  {
    atomicNumber: 76,
    symbol: "Os",
    name: "Osmium",
    atomicMass: 190.23,
    category: "transition-metal",
    group: 8,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: 2.2,
    atomicRadius: 135,
    ionizationEnergy: 8.7,
    meltingPoint: 3033,
    boilingPoint: 5012,
    density: 22.59,
    state: "solid",
    discoveryYear: 1803,
    description: "Osmium is a hard, brittle, bluish-white transition metal in the platinum group. It is the densest naturally occurring element and has a high melting point.",
    uses: ["Alloys", "Electrical contacts", "Fountain pen tips"],
  },
  {
    atomicNumber: 77,
    symbol: "Ir",
    name: "Iridium",
    atomicMass: 192.22,
    category: "transition-metal",
    group: 9,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: 2.2,
    atomicRadius: 136,
    ionizationEnergy: 9.1,
    meltingPoint: 2446,
    boilingPoint: 4428,
    density: 22.56,
    state: "solid",
    discoveryYear: 1803,
    description: "Iridium is a very hard, brittle, silvery-white transition metal of the platinum group. It is the second-densest element and the most corrosion-resistant metal.",
    uses: ["Spark plugs", "Crucibles", "Electrical contacts"],
  },
  {
    atomicNumber: 78,
    symbol: "Pt",
    name: "Platinum",
    atomicMass: 195.08,
    category: "transition-metal",
    group: 10,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: 2.28,
    atomicRadius: 139,
    ionizationEnergy: 9.0,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    density: 21.45,
    state: "solid",
    discoveryYear: 1735,
    description: "Platinum is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal. It is one of the rarest elements in Earth's crust.",
    uses: ["Catalytic converters", "Jewelry", "Laboratory equipment"],
  },
  {
    atomicNumber: 79,
    symbol: "Au",
    name: "Gold",
    atomicMass: 196.97,
    category: "transition-metal",
    group: 11,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: 2.54,
    atomicRadius: 144,
    ionizationEnergy: 9.226,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    density: 19.3,
    state: "solid",
    discoveryYear: null,
    description: "Gold is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. It is one of the least reactive chemical elements and is solid under standard conditions.",
    uses: ["Jewelry", "Electronics", "Currency"],
  },
  {
    atomicNumber: 80,
    symbol: "Hg",
    name: "Mercury",
    atomicMass: 200.59,
    category: "transition-metal",
    group: 12,
    period: 6,
    block: "d",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: 2.0,
    atomicRadius: 151,
    ionizationEnergy: 10.438,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    density: 13.534,
    state: "liquid",
    discoveryYear: null,
    description: "Mercury is a heavy, silvery-white liquid metal. It is the only metallic element that is liquid at standard conditions for temperature and pressure.",
    uses: ["Thermometers (historical)", "Dental amalgams", "Electrical switches"],
  },
  {
    atomicNumber: 104,
    symbol: "Rf",
    name: "Rutherfordium",
    atomicMass: 267,
    category: "transition-metal",
    group: 4,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1969,
    description: "Rutherfordium is a synthetic element named after Ernest Rutherford. As a superheavy element, it has only been produced in laboratories in very small quantities.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 105,
    symbol: "Db",
    name: "Dubnium",
    atomicMass: 268,
    category: "transition-metal",
    group: 5,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1970,
    description: "Dubnium is a synthetic element named after the Russian town of Dubna. Like other superheavy elements, it has only been produced in laboratories in tiny quantities.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 106,
    symbol: "Sg",
    name: "Seaborgium",
    atomicMass: 269,
    category: "transition-metal",
    group: 6,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1974,
    description: "Seaborgium is a synthetic element named after American nuclear chemist Glenn T. Seaborg. It is produced artificially in particle accelerators.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 107,
    symbol: "Bh",
    name: "Bohrium",
    atomicMass: 270,
    category: "transition-metal",
    group: 7,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1981,
    description: "Bohrium is a synthetic element named after Danish physicist Niels Bohr. It has only been produced in very small amounts in laboratories.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 108,
    symbol: "Hs",
    name: "Hassium",
    atomicMass: 277,
    category: "transition-metal",
    group: 8,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1984,
    description: "Hassium is a synthetic element named after the German state of Hesse. Like other superheavy elements, it is highly unstable and has only been produced in tiny quantities.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 109,
    symbol: "Mt",
    name: "Meitnerium",
    atomicMass: 278,
    category: "transition-metal",
    group: 9,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1982,
    description: "Meitnerium is a synthetic element named after Austrian physicist Lise Meitner. It has been produced only in extremely small amounts in laboratories.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 110,
    symbol: "Ds",
    name: "Darmstadtium",
    atomicMass: 281,
    category: "transition-metal",
    group: 10,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1994,
    description: "Darmstadtium is a synthetic element named after Darmstadt, Germany, where it was discovered. Due to its extreme instability, very little is known about its properties.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 111,
    symbol: "Rg",
    name: "Roentgenium",
    atomicMass: 282,
    category: "transition-metal",
    group: 11,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1994,
    description: "Roentgenium is a synthetic element named after Wilhelm Röntgen. As a superheavy element, it is highly unstable and has only been produced in small quantities in laboratories.",
    uses: ["Scientific research"],
  },
  {
    atomicNumber: 112,
    symbol: "Cn",
    name: "Copernicium",
    atomicMass: 285,
    category: "transition-metal",
    group: 12,
    period: 7,
    block: "d",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    electronegativity: null,
    atomicRadius: null,
    ionizationEnergy: null,
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    state: "solid",
    discoveryYear: 1996,
    description: "Copernicium is a synthetic element named after astronomer Nicolaus Copernicus. Only a few atoms have ever been produced.",
    uses: ["Scientific research"],
  }
];
